export interface StandardFieldDef {
  key: string;
  label: string;
  type: 'text' | 'textarea' | 'number' | 'currency' | 'date' | 'datetime' | 'select' | 'combobox';
  defaultOptions?: string[];
  /** When true, options are loaded dynamically (e.g. org members) and cannot be edited here. */
  dynamicOptions?: boolean;
}

export const STANDARD_FIELDS: StandardFieldDef[] = [
  { key: 'first_name', label: 'Nome', type: 'text' },
  { key: 'last_name', label: 'Sobrenome', type: 'text' },
  { key: 'email', label: 'E-mail', type: 'text' },
  { key: 'telefone', label: 'Telefone', type: 'text' },
  {
    key: 'job_title',
    label: 'Cargo',
    type: 'combobox',
    defaultOptions: [
      'Proprietário',
      'Sócio',
      'CEO/Diretor Executivo',
      'Diretor',
      'Gerente',
      'Supervisor',
      'Coordenador',
      'Analista',
      'Assistente/Funcionário',
      'Decisor',
    ],
  },
  { key: 'cnpj', label: 'CNPJ', type: 'text' },
  { key: 'nome_fantasia', label: 'Empresa', type: 'text' },
  {
    key: 'lead_source',
    label: 'Origem',
    type: 'select',
    defaultOptions: [
      'Outbound',
      'Inbound Marketing',
      'Indicação',
      'LinkedIn',
      'Evento',
      'Site',
      'Apollo.io',
      'Outro',
    ],
  },
  {
    key: 'canal',
    label: 'Sub-origem',
    type: 'select',
    defaultOptions: [
      'Facebook',
      'Google',
      'Instagram',
      'Orgânico',
      'TikTok',
      'LinkedIn',
      'Indicação',
      'Bing',
      'Prospecção Fria',
    ],
  },
  { key: 'assigned_to', label: 'SDR Responsável', type: 'select', dynamicOptions: true },
  {
    key: 'segmento',
    label: 'Segmento',
    type: 'select',
    defaultOptions: [
      'Agronegócio',
      'Aplicativo',
      'Automotivo',
      'Bens de Consumo',
      'Casa e Decoração',
      'Construção/Imobiliária',
      'Consultoria',
      'Cosmética',
      'E-commerce',
      'Educação',
      'Energia solar',
      'Estética',
      'Farmácia',
      'Finanças',
      'Food Service',
      'Franquia',
      'Indústria',
      'Logística',
      'Moda',
      'ONG',
      'PDV',
      'Prestação de serviços',
      'SaaS',
      'Saúde e Fitness',
      'Serviço',
      'Tecnologia e StartUp',
      'Telecom',
      'Turismo',
      'Varejo',
      'Outro',
    ],
  },
  { key: 'instagram', label: 'Instagram', type: 'text' },
  { key: 'linkedin', label: 'LinkedIn', type: 'text' },
  { key: 'website', label: 'Website', type: 'text' },
  { key: 'created_at', label: 'Data de Inscrição', type: 'date' },
];
