-- ============================================================================
-- Flux Sales Engagement 2.0 — Initial Schema Migration
-- ============================================================================
-- Generated by @data-engineer (Dara) based on architecture.md review
-- Includes all CRITICAL, HIGH, and MEDIUM fixes from schema review
-- ============================================================================
-- ROLLBACK: See 20260219_000001_initial_schema_rollback.sql
-- ============================================================================

BEGIN;

-- ============================================================================
-- 1. EXTENSIONS
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "pg_cron";
CREATE EXTENSION IF NOT EXISTS "pg_net";

-- ============================================================================
-- 2. ENUM TYPES
-- ============================================================================

CREATE TYPE member_role AS ENUM ('manager', 'sdr');

-- [CRITICAL #2] member_status como enum, não TEXT
CREATE TYPE member_status AS ENUM ('invited', 'active', 'suspended', 'removed');

CREATE TYPE lead_status AS ENUM ('new', 'contacted', 'qualified', 'unqualified', 'archived');
CREATE TYPE enrichment_status AS ENUM ('pending', 'enriching', 'enriched', 'enrichment_failed', 'not_found');
CREATE TYPE import_status AS ENUM ('processing', 'completed', 'failed');
CREATE TYPE cadence_status AS ENUM ('draft', 'active', 'paused', 'archived');
CREATE TYPE enrollment_status AS ENUM ('active', 'paused', 'completed', 'replied', 'bounced', 'unsubscribed');
CREATE TYPE channel_type AS ENUM ('email', 'whatsapp');
CREATE TYPE interaction_type AS ENUM ('sent', 'delivered', 'opened', 'clicked', 'replied', 'bounced', 'failed', 'meeting_scheduled');
CREATE TYPE crm_type AS ENUM ('hubspot', 'pipedrive', 'rdstation');
CREATE TYPE connection_status AS ENUM ('connected', 'disconnected', 'error', 'syncing');
CREATE TYPE subscription_status AS ENUM ('active', 'past_due', 'canceled', 'trialing');

-- [HIGH #7] sync_direction como enum
CREATE TYPE sync_direction AS ENUM ('push', 'pull');

-- ============================================================================
-- 3. CORE TABLES (ordenação corrigida por dependências — fix #5)
-- ============================================================================

-- 3.1 Organizations
CREATE TABLE organizations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  owner_id UUID REFERENCES auth.users(id) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE organizations IS 'Organizações (tenants) do sistema multi-tenant';
COMMENT ON COLUMN organizations.slug IS 'Slug único para URL e identificação';
COMMENT ON COLUMN organizations.owner_id IS 'Usuário que criou a organização (primeiro manager)';

-- 3.2 Organization Members
CREATE TABLE organization_members (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID REFERENCES organizations(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  role member_role NOT NULL DEFAULT 'sdr',
  -- [CRITICAL #2] status como enum member_status
  status member_status NOT NULL DEFAULT 'invited',
  invited_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  accepted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(org_id, user_id)
);

COMMENT ON TABLE organization_members IS 'Membros da organização com papel (manager/sdr)';

-- 3.3 Plans (antes de subscriptions, que depende dele)
CREATE TABLE plans (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  price_cents INTEGER NOT NULL,
  max_leads INTEGER NOT NULL,
  max_ai_per_day INTEGER NOT NULL,
  max_whatsapp_per_month INTEGER NOT NULL,
  included_users INTEGER NOT NULL DEFAULT 4,
  additional_user_price_cents INTEGER NOT NULL,
  features JSONB NOT NULL DEFAULT '{}',
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- [HIGH #6] CHECK constraints
  CONSTRAINT chk_plans_price_positive CHECK (price_cents >= 0),
  CONSTRAINT chk_plans_max_leads CHECK (max_leads > 0),
  CONSTRAINT chk_plans_included_users CHECK (included_users > 0),
  CONSTRAINT chk_plans_additional_user_price CHECK (additional_user_price_cents >= 0)
);

COMMENT ON TABLE plans IS 'Planos de assinatura (Starter, Pro, Enterprise)';
COMMENT ON COLUMN plans.max_ai_per_day IS 'Limite diário de gerações AI. -1 = ilimitado';
COMMENT ON COLUMN plans.features IS 'Features JSON: {enrichment, crm, calendar}';

-- 3.4 Subscriptions
CREATE TABLE subscriptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID REFERENCES organizations(id) ON DELETE CASCADE NOT NULL,
  plan_id UUID REFERENCES plans(id) NOT NULL,
  status subscription_status NOT NULL DEFAULT 'trialing',
  current_period_start TIMESTAMPTZ NOT NULL DEFAULT now(),
  current_period_end TIMESTAMPTZ NOT NULL DEFAULT now() + INTERVAL '30 days',
  stripe_subscription_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- [MEDIUM #12] updated_at para tracking de mudanças de status
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(org_id)
);

COMMENT ON TABLE subscriptions IS 'Assinatura ativa da organização (1 por org)';

-- 3.5 Lead Imports (antes de leads, que referencia import_id)
CREATE TABLE lead_imports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID REFERENCES organizations(id) ON DELETE CASCADE NOT NULL,
  file_name TEXT NOT NULL,
  total_rows INTEGER NOT NULL DEFAULT 0,
  processed_rows INTEGER NOT NULL DEFAULT 0,
  success_count INTEGER NOT NULL DEFAULT 0,
  error_count INTEGER NOT NULL DEFAULT 0,
  status import_status NOT NULL DEFAULT 'processing',
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- [HIGH #6] CHECK constraints
  CONSTRAINT chk_imports_rows_positive CHECK (total_rows >= 0),
  CONSTRAINT chk_imports_processed CHECK (processed_rows >= 0 AND processed_rows <= total_rows),
  CONSTRAINT chk_imports_counts CHECK (success_count >= 0 AND error_count >= 0)
);

COMMENT ON TABLE lead_imports IS 'Registro de importações CSV de leads';

-- 3.6 Leads
CREATE TABLE leads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID REFERENCES organizations(id) ON DELETE CASCADE NOT NULL,
  -- [HIGH #6] CNPJ com CHECK de formato (14 dígitos)
  cnpj TEXT NOT NULL CONSTRAINT chk_leads_cnpj_format CHECK (cnpj ~ '^\d{14}$'),
  status lead_status NOT NULL DEFAULT 'new',
  enrichment_status enrichment_status NOT NULL DEFAULT 'pending',
  razao_social TEXT,
  nome_fantasia TEXT,
  endereco JSONB,
  porte TEXT,
  cnae TEXT,
  situacao_cadastral TEXT,
  email TEXT,
  telefone TEXT,
  socios JSONB,
  faturamento_estimado NUMERIC(15,2),
  enriched_at TIMESTAMPTZ,
  created_by UUID REFERENCES auth.users(id),
  -- [CRITICAL #1] FK para lead_imports com ON DELETE SET NULL
  import_id UUID REFERENCES lead_imports(id) ON DELETE SET NULL,
  -- [MEDIUM #13] Soft delete
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(org_id, cnpj)
);

COMMENT ON TABLE leads IS 'Leads de vendas importados via CSV ou criados manualmente';
COMMENT ON COLUMN leads.cnpj IS 'CNPJ com 14 dígitos sem formatação';
COMMENT ON COLUMN leads.enrichment_status IS 'Status do enrichment via CNPJ.ws ou Lemit';
COMMENT ON COLUMN leads.endereco IS 'Endereço completo em JSONB: {logradouro, numero, complemento, bairro, cidade, uf, cep}';
COMMENT ON COLUMN leads.socios IS 'Lista de sócios em JSONB: [{nome, qualificacao, cpf_masked}]';
COMMENT ON COLUMN leads.deleted_at IS 'Soft delete — NULL = ativo, TIMESTAMPTZ = excluído';

-- 3.7 Lead Import Errors
CREATE TABLE lead_import_errors (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  import_id UUID REFERENCES lead_imports(id) ON DELETE CASCADE NOT NULL,
  row_number INTEGER NOT NULL,
  cnpj TEXT,
  error_message TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_import_errors_row CHECK (row_number > 0)
);

COMMENT ON TABLE lead_import_errors IS 'Erros encontrados durante importação CSV de leads';

-- [MEDIUM #11] Enrichment Attempts — log de tentativas de enrichment
CREATE TABLE enrichment_attempts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id UUID REFERENCES leads(id) ON DELETE CASCADE NOT NULL,
  provider TEXT NOT NULL, -- 'cnpj_ws', 'lemit'
  status enrichment_status NOT NULL,
  response_data JSONB,
  error_message TEXT,
  duration_ms INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_enrichment_provider CHECK (provider IN ('cnpj_ws', 'lemit'))
);

COMMENT ON TABLE enrichment_attempts IS 'Log de tentativas de enrichment (retry, auditoria, debugging)';
COMMENT ON COLUMN enrichment_attempts.provider IS 'Provedor usado: cnpj_ws (gratuito) ou lemit (premium)';

-- 3.8 Message Templates (ANTES de cadence_steps — fix #5)
CREATE TABLE message_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID REFERENCES organizations(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  channel channel_type NOT NULL,
  subject TEXT,
  body TEXT NOT NULL,
  variables_used TEXT[] DEFAULT '{}',
  is_system BOOLEAN NOT NULL DEFAULT false,
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE message_templates IS 'Templates de mensagem para email e WhatsApp';
COMMENT ON COLUMN message_templates.variables_used IS 'Lista de variáveis usadas: {nome_fantasia, razao_social, ...}';
COMMENT ON COLUMN message_templates.is_system IS 'Templates do sistema não podem ser editados pelo usuário';

-- 3.9 Cadences
CREATE TABLE cadences (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID REFERENCES organizations(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  status cadence_status NOT NULL DEFAULT 'draft',
  total_steps INTEGER NOT NULL DEFAULT 0,
  created_by UUID REFERENCES auth.users(id),
  -- [MEDIUM #13] Soft delete
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_cadences_total_steps CHECK (total_steps >= 0)
);

COMMENT ON TABLE cadences IS 'Cadências de prospecção (sequências automatizadas de contato)';

-- 3.10 Cadence Steps (agora DEPOIS de message_templates — fix #5)
CREATE TABLE cadence_steps (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  cadence_id UUID REFERENCES cadences(id) ON DELETE CASCADE NOT NULL,
  step_order INTEGER NOT NULL,
  channel channel_type NOT NULL,
  template_id UUID REFERENCES message_templates(id) ON DELETE SET NULL,
  delay_days INTEGER NOT NULL DEFAULT 0,
  delay_hours INTEGER NOT NULL DEFAULT 0,
  ai_personalization BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(cadence_id, step_order),
  -- [HIGH #6] CHECK: delays não-negativos
  CONSTRAINT chk_steps_delay_positive CHECK (delay_days >= 0 AND delay_hours >= 0),
  CONSTRAINT chk_steps_order_positive CHECK (step_order > 0)
);

COMMENT ON TABLE cadence_steps IS 'Passos individuais dentro de uma cadência';
COMMENT ON COLUMN cadence_steps.delay_days IS 'Dias de espera antes de executar este passo';
COMMENT ON COLUMN cadence_steps.ai_personalization IS 'Se true, mensagem será personalizada por AI antes do envio';

-- 3.11 Cadence Enrollments
CREATE TABLE cadence_enrollments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  cadence_id UUID REFERENCES cadences(id) ON DELETE CASCADE NOT NULL,
  lead_id UUID REFERENCES leads(id) ON DELETE CASCADE NOT NULL,
  current_step INTEGER NOT NULL DEFAULT 1,
  status enrollment_status NOT NULL DEFAULT 'active',
  next_step_due TIMESTAMPTZ,
  enrolled_by UUID REFERENCES auth.users(id),
  enrolled_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  -- [MEDIUM #12] updated_at para tracking
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_enrollments_step_positive CHECK (current_step > 0)
);

COMMENT ON TABLE cadence_enrollments IS 'Inscrição de leads em cadências de prospecção';
COMMENT ON COLUMN cadence_enrollments.next_step_due IS 'Calculado automaticamente pelo trigger set_next_step_due';

-- 3.12 Interactions (tabela de eventos — append-only)
CREATE TABLE interactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID REFERENCES organizations(id) ON DELETE CASCADE NOT NULL,
  lead_id UUID REFERENCES leads(id) ON DELETE CASCADE NOT NULL,
  cadence_id UUID REFERENCES cadences(id) ON DELETE SET NULL,
  step_id UUID REFERENCES cadence_steps(id) ON DELETE SET NULL,
  channel channel_type NOT NULL,
  type interaction_type NOT NULL,
  message_content TEXT,
  external_id TEXT,
  metadata JSONB,
  ai_generated BOOLEAN NOT NULL DEFAULT false,
  original_template_id UUID REFERENCES message_templates(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE interactions IS 'Registro de todas as interações com leads (append-only)';
COMMENT ON COLUMN interactions.external_id IS 'ID externo do provedor (Gmail message ID, WhatsApp message ID)';
COMMENT ON COLUMN interactions.metadata IS 'Metadados extras: {gmail_thread_id, wa_status, open_count, click_urls}';
COMMENT ON COLUMN interactions.ai_generated IS 'Se true, conteúdo foi gerado/personalizado por AI';

-- 3.13 CRM Connections
CREATE TABLE crm_connections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID REFERENCES organizations(id) ON DELETE CASCADE NOT NULL,
  crm_provider crm_type NOT NULL,
  credentials_encrypted JSONB NOT NULL,
  field_mapping JSONB,
  status connection_status NOT NULL DEFAULT 'disconnected',
  last_sync_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- [MEDIUM #12] updated_at
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- [CRITICAL #4] Permite múltiplos CRMs por org (1 por provider)
  UNIQUE(org_id, crm_provider)
);

COMMENT ON TABLE crm_connections IS 'Conexões CRM (HubSpot, Pipedrive, RD Station)';
COMMENT ON COLUMN crm_connections.credentials_encrypted IS 'Credenciais criptografadas (NUNCA expor em logs)';
COMMENT ON COLUMN crm_connections.field_mapping IS 'Mapeamento de campos Flux→CRM em JSONB';

-- 3.14 CRM Sync Log
CREATE TABLE crm_sync_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  connection_id UUID REFERENCES crm_connections(id) ON DELETE CASCADE NOT NULL,
  -- [HIGH #7] direction como enum
  direction sync_direction NOT NULL,
  records_synced INTEGER NOT NULL DEFAULT 0,
  errors INTEGER NOT NULL DEFAULT 0,
  duration_ms INTEGER,
  error_details JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_sync_records CHECK (records_synced >= 0 AND errors >= 0)
);

COMMENT ON TABLE crm_sync_log IS 'Log de sincronizações CRM (auditoria e debugging)';

-- 3.15 AI Usage (daily tracking)
CREATE TABLE ai_usage (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID REFERENCES organizations(id) ON DELETE CASCADE NOT NULL,
  usage_date DATE NOT NULL DEFAULT CURRENT_DATE,
  generation_count INTEGER NOT NULL DEFAULT 0,
  daily_limit INTEGER NOT NULL,
  UNIQUE(org_id, usage_date),
  -- [HIGH #6] CHECK constraints
  CONSTRAINT chk_ai_usage_positive CHECK (generation_count >= 0),
  CONSTRAINT chk_ai_usage_limit CHECK (daily_limit > 0 OR daily_limit = -1)
);

COMMENT ON TABLE ai_usage IS 'Tracking diário de uso de AI por organização';
COMMENT ON COLUMN ai_usage.daily_limit IS 'Limite diário. -1 = ilimitado (Enterprise)';

-- 3.16 WhatsApp Credits (monthly tracking)
CREATE TABLE whatsapp_credits (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID REFERENCES organizations(id) ON DELETE CASCADE NOT NULL,
  plan_credits INTEGER NOT NULL DEFAULT 0,
  used_credits INTEGER NOT NULL DEFAULT 0,
  overage_count INTEGER NOT NULL DEFAULT 0,
  -- [MEDIUM #14] Validação de formato do período
  period TEXT NOT NULL CONSTRAINT chk_wa_period_format CHECK (period ~ '^\d{4}-\d{2}$'),
  UNIQUE(org_id, period),
  -- [HIGH #6] CHECK constraints
  CONSTRAINT chk_wa_credits_positive CHECK (plan_credits >= 0 AND used_credits >= 0 AND overage_count >= 0)
);

COMMENT ON TABLE whatsapp_credits IS 'Créditos mensais de WhatsApp por organização';
COMMENT ON COLUMN whatsapp_credits.period IS 'Período no formato YYYY-MM (ex: 2026-02)';

-- 3.17 Gmail Connections
CREATE TABLE gmail_connections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID REFERENCES organizations(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  access_token_encrypted TEXT NOT NULL,
  refresh_token_encrypted TEXT NOT NULL,
  token_expires_at TIMESTAMPTZ NOT NULL,
  email_address TEXT NOT NULL,
  status connection_status NOT NULL DEFAULT 'connected',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- [MEDIUM #12] updated_at para tracking de token refresh
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(org_id, user_id)
);

COMMENT ON TABLE gmail_connections IS 'Conexões OAuth2 com Gmail por usuário';
COMMENT ON COLUMN gmail_connections.access_token_encrypted IS 'Token criptografado (NUNCA expor)';

-- 3.18 WhatsApp Connections
CREATE TABLE whatsapp_connections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID REFERENCES organizations(id) ON DELETE CASCADE NOT NULL,
  phone_number_id TEXT NOT NULL,
  business_account_id TEXT NOT NULL,
  access_token_encrypted TEXT NOT NULL,
  status connection_status NOT NULL DEFAULT 'disconnected',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- [MEDIUM #12] updated_at
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(org_id)
);

COMMENT ON TABLE whatsapp_connections IS 'Conexão WhatsApp Business API por organização (1 por org)';

-- 3.19 Calendar Connections
CREATE TABLE calendar_connections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID REFERENCES organizations(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  access_token_encrypted TEXT NOT NULL,
  refresh_token_encrypted TEXT NOT NULL,
  token_expires_at TIMESTAMPTZ NOT NULL,
  calendar_email TEXT NOT NULL,
  status connection_status NOT NULL DEFAULT 'connected',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- [MEDIUM #12] updated_at
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(org_id, user_id)
);

COMMENT ON TABLE calendar_connections IS 'Conexões Google Calendar por usuário';

-- ============================================================================
-- 4. INDEXES
-- ============================================================================

-- 4.1 Leads indexes
CREATE INDEX idx_leads_org ON leads(org_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_leads_status ON leads(org_id, status) WHERE deleted_at IS NULL;
CREATE INDEX idx_leads_enrichment ON leads(org_id, enrichment_status) WHERE deleted_at IS NULL;
CREATE INDEX idx_leads_cnpj ON leads(org_id, cnpj);
CREATE INDEX idx_leads_porte ON leads(org_id, porte) WHERE deleted_at IS NULL;
CREATE INDEX idx_leads_cnae ON leads(org_id, cnae) WHERE deleted_at IS NULL;
CREATE INDEX idx_leads_created ON leads(org_id, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_leads_import ON leads(import_id) WHERE import_id IS NOT NULL;

-- Full-text search on leads (portuguese config)
CREATE INDEX idx_leads_search ON leads USING GIN(
  to_tsvector('portuguese', coalesce(razao_social, '') || ' ' || coalesce(nome_fantasia, '') || ' ' || coalesce(cnpj, ''))
) WHERE deleted_at IS NULL;

-- 4.2 Members indexes
CREATE INDEX idx_members_user ON organization_members(user_id) WHERE status = 'active';
CREATE INDEX idx_members_org ON organization_members(org_id);

-- 4.3 Cadence indexes
CREATE INDEX idx_cadences_org ON cadences(org_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_cadence_steps_cadence ON cadence_steps(cadence_id, step_order);

-- 4.4 Enrollment indexes (critical for execution engine)
CREATE INDEX idx_enrollments_active ON cadence_enrollments(status, next_step_due)
  WHERE status = 'active';
CREATE INDEX idx_enrollments_cadence ON cadence_enrollments(cadence_id);
CREATE INDEX idx_enrollments_lead ON cadence_enrollments(lead_id);

-- Prevent duplicate active enrollment
CREATE UNIQUE INDEX idx_enrollments_unique_active ON cadence_enrollments(cadence_id, lead_id)
  WHERE status IN ('active', 'paused');

-- 4.5 Interaction indexes
CREATE INDEX idx_interactions_lead ON interactions(lead_id, created_at DESC);
CREATE INDEX idx_interactions_cadence ON interactions(cadence_id) WHERE cadence_id IS NOT NULL;
CREATE INDEX idx_interactions_org ON interactions(org_id, created_at DESC);
-- [MEDIUM #15] Index por tipo para dashboard
CREATE INDEX idx_interactions_type ON interactions(org_id, type, created_at DESC);

-- 4.6 Usage tracking
CREATE INDEX idx_ai_usage_org_date ON ai_usage(org_id, usage_date);
CREATE INDEX idx_wa_credits_org_period ON whatsapp_credits(org_id, period);

-- 4.7 Enrichment attempts
CREATE INDEX idx_enrichment_attempts_lead ON enrichment_attempts(lead_id, created_at DESC);

-- 4.8 CRM sync log
CREATE INDEX idx_crm_sync_connection ON crm_sync_log(connection_id, created_at DESC);

-- 4.9 Soft delete partial indexes
CREATE INDEX idx_leads_deleted ON leads(org_id, deleted_at) WHERE deleted_at IS NOT NULL;
CREATE INDEX idx_cadences_deleted ON cadences(org_id, deleted_at) WHERE deleted_at IS NOT NULL;

-- ============================================================================
-- 5. RLS HELPER FUNCTIONS
-- ============================================================================

-- [CRITICAL #3] user_org_id com ORDER BY determinístico
CREATE OR REPLACE FUNCTION public.user_org_id()
RETURNS UUID AS $$
  SELECT org_id FROM organization_members
  WHERE user_id = auth.uid() AND status = 'active'
  ORDER BY accepted_at DESC NULLS LAST
  LIMIT 1;
$$ LANGUAGE sql SECURITY DEFINER STABLE SET search_path = public;

COMMENT ON FUNCTION public.user_org_id IS 'Retorna org_id do usuário autenticado. Usa membro mais recentemente aceito. SECURITY DEFINER.';

-- Helper: check if user is manager
CREATE OR REPLACE FUNCTION public.is_manager()
RETURNS BOOLEAN AS $$
  SELECT EXISTS (
    SELECT 1 FROM organization_members
    WHERE user_id = auth.uid()
    AND role = 'manager'
    AND status = 'active'
  );
$$ LANGUAGE sql SECURITY DEFINER STABLE SET search_path = public;

COMMENT ON FUNCTION public.is_manager IS 'Verifica se usuário autenticado é manager na org. SECURITY DEFINER.';

-- ============================================================================
-- 6. ENABLE RLS ON ALL TABLES
-- ============================================================================

ALTER TABLE organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE lead_imports ENABLE ROW LEVEL SECURITY;
-- [HIGH #8] Tabelas que estavam sem RLS
ALTER TABLE lead_import_errors ENABLE ROW LEVEL SECURITY;
ALTER TABLE enrichment_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE cadences ENABLE ROW LEVEL SECURITY;
ALTER TABLE cadence_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE cadence_enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE message_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE interactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm_sync_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE whatsapp_credits ENABLE ROW LEVEL SECURITY;
-- [HIGH #8] Conexões sem RLS no original
ALTER TABLE gmail_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE whatsapp_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE calendar_connections ENABLE ROW LEVEL SECURITY;
-- Plans: público para leitura (sem write via client)
ALTER TABLE plans ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- 7. RLS POLICIES
-- ============================================================================

-- 7.1 Organizations
CREATE POLICY "org_member_read" ON organizations FOR SELECT
  USING (id = public.user_org_id());

CREATE POLICY "org_owner_update" ON organizations FOR UPDATE
  USING (owner_id = auth.uid());

-- 7.2 Organization Members
CREATE POLICY "members_org_read" ON organization_members FOR SELECT
  USING (org_id = public.user_org_id());

CREATE POLICY "members_manager_insert" ON organization_members FOR INSERT
  WITH CHECK (org_id = public.user_org_id() AND public.is_manager());

CREATE POLICY "members_manager_update" ON organization_members FOR UPDATE
  USING (org_id = public.user_org_id() AND public.is_manager());

CREATE POLICY "members_manager_delete" ON organization_members FOR DELETE
  USING (org_id = public.user_org_id() AND public.is_manager());

-- 7.3 Leads
CREATE POLICY "leads_org_read" ON leads FOR SELECT
  USING (org_id = public.user_org_id());

CREATE POLICY "leads_org_insert" ON leads FOR INSERT
  WITH CHECK (org_id = public.user_org_id());

CREATE POLICY "leads_org_update" ON leads FOR UPDATE
  USING (org_id = public.user_org_id());

CREATE POLICY "leads_org_delete" ON leads FOR DELETE
  USING (org_id = public.user_org_id());

-- 7.4 Lead Imports
CREATE POLICY "imports_org_read" ON lead_imports FOR SELECT
  USING (org_id = public.user_org_id());

CREATE POLICY "imports_org_insert" ON lead_imports FOR INSERT
  WITH CHECK (org_id = public.user_org_id());

-- [HIGH #8] Lead Import Errors — via import's org
CREATE POLICY "import_errors_via_import" ON lead_import_errors FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM lead_imports
    WHERE lead_imports.id = lead_import_errors.import_id
    AND lead_imports.org_id = public.user_org_id()
  ));

CREATE POLICY "import_errors_insert" ON lead_import_errors FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1 FROM lead_imports
    WHERE lead_imports.id = lead_import_errors.import_id
    AND lead_imports.org_id = public.user_org_id()
  ));

-- [MEDIUM #11] Enrichment Attempts — via lead's org
CREATE POLICY "enrichment_attempts_via_lead" ON enrichment_attempts FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM leads
    WHERE leads.id = enrichment_attempts.lead_id
    AND leads.org_id = public.user_org_id()
  ));

-- 7.5 Cadences
CREATE POLICY "cadences_org_read" ON cadences FOR SELECT
  USING (org_id = public.user_org_id());

CREATE POLICY "cadences_org_insert" ON cadences FOR INSERT
  WITH CHECK (org_id = public.user_org_id());

CREATE POLICY "cadences_org_update" ON cadences FOR UPDATE
  USING (org_id = public.user_org_id());

CREATE POLICY "cadences_org_delete" ON cadences FOR DELETE
  USING (org_id = public.user_org_id());

-- [HIGH #9] Steps: EXISTS em vez de IN para performance
CREATE POLICY "steps_via_cadence_read" ON cadence_steps FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM cadences
    WHERE cadences.id = cadence_steps.cadence_id
    AND cadences.org_id = public.user_org_id()
  ));

CREATE POLICY "steps_via_cadence_insert" ON cadence_steps FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1 FROM cadences
    WHERE cadences.id = cadence_steps.cadence_id
    AND cadences.org_id = public.user_org_id()
  ));

CREATE POLICY "steps_via_cadence_update" ON cadence_steps FOR UPDATE
  USING (EXISTS (
    SELECT 1 FROM cadences
    WHERE cadences.id = cadence_steps.cadence_id
    AND cadences.org_id = public.user_org_id()
  ));

CREATE POLICY "steps_via_cadence_delete" ON cadence_steps FOR DELETE
  USING (EXISTS (
    SELECT 1 FROM cadences
    WHERE cadences.id = cadence_steps.cadence_id
    AND cadences.org_id = public.user_org_id()
  ));

-- [HIGH #9] Enrollments: EXISTS em vez de IN
CREATE POLICY "enrollments_via_cadence_read" ON cadence_enrollments FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM cadences
    WHERE cadences.id = cadence_enrollments.cadence_id
    AND cadences.org_id = public.user_org_id()
  ));

CREATE POLICY "enrollments_via_cadence_insert" ON cadence_enrollments FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1 FROM cadences
    WHERE cadences.id = cadence_enrollments.cadence_id
    AND cadences.org_id = public.user_org_id()
  ));

CREATE POLICY "enrollments_via_cadence_update" ON cadence_enrollments FOR UPDATE
  USING (EXISTS (
    SELECT 1 FROM cadences
    WHERE cadences.id = cadence_enrollments.cadence_id
    AND cadences.org_id = public.user_org_id()
  ));

-- 7.6 Message Templates
CREATE POLICY "templates_org_read" ON message_templates FOR SELECT
  USING (org_id = public.user_org_id());

CREATE POLICY "templates_org_insert" ON message_templates FOR INSERT
  WITH CHECK (org_id = public.user_org_id());

CREATE POLICY "templates_org_update" ON message_templates FOR UPDATE
  USING (org_id = public.user_org_id());

CREATE POLICY "templates_org_delete" ON message_templates FOR DELETE
  USING (org_id = public.user_org_id() AND is_system = false);

-- 7.7 Interactions (append-only para client, read own org)
CREATE POLICY "interactions_org_read" ON interactions FOR SELECT
  USING (org_id = public.user_org_id());

CREATE POLICY "interactions_org_insert" ON interactions FOR INSERT
  WITH CHECK (org_id = public.user_org_id());

-- 7.8 CRM Connections (manager only)
CREATE POLICY "crm_manager_read" ON crm_connections FOR SELECT
  USING (org_id = public.user_org_id() AND public.is_manager());

CREATE POLICY "crm_manager_insert" ON crm_connections FOR INSERT
  WITH CHECK (org_id = public.user_org_id() AND public.is_manager());

CREATE POLICY "crm_manager_update" ON crm_connections FOR UPDATE
  USING (org_id = public.user_org_id() AND public.is_manager());

CREATE POLICY "crm_manager_delete" ON crm_connections FOR DELETE
  USING (org_id = public.user_org_id() AND public.is_manager());

-- [HIGH #8] CRM Sync Log — via connection's org (manager only)
CREATE POLICY "crm_sync_log_read" ON crm_sync_log FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM crm_connections
    WHERE crm_connections.id = crm_sync_log.connection_id
    AND crm_connections.org_id = public.user_org_id()
    AND public.is_manager()
  ));

-- 7.9 Subscriptions (org members can read, only system writes)
CREATE POLICY "subscriptions_org_read" ON subscriptions FOR SELECT
  USING (org_id = public.user_org_id());

-- 7.10 Usage tracking (org members can read)
CREATE POLICY "ai_usage_org_read" ON ai_usage FOR SELECT
  USING (org_id = public.user_org_id());

CREATE POLICY "wa_credits_org_read" ON whatsapp_credits FOR SELECT
  USING (org_id = public.user_org_id());

-- [HIGH #8] Plans: público para leitura (todos os planos visíveis)
CREATE POLICY "plans_public_read" ON plans FOR SELECT
  USING (active = true);

-- [HIGH #8] Gmail Connections — user owns their own connection
CREATE POLICY "gmail_own_read" ON gmail_connections FOR SELECT
  USING (org_id = public.user_org_id() AND user_id = auth.uid());

CREATE POLICY "gmail_own_insert" ON gmail_connections FOR INSERT
  WITH CHECK (org_id = public.user_org_id() AND user_id = auth.uid());

CREATE POLICY "gmail_own_update" ON gmail_connections FOR UPDATE
  USING (org_id = public.user_org_id() AND user_id = auth.uid());

CREATE POLICY "gmail_own_delete" ON gmail_connections FOR DELETE
  USING (org_id = public.user_org_id() AND user_id = auth.uid());

-- [HIGH #8] WhatsApp Connections — manager only (org-level)
CREATE POLICY "whatsapp_manager_read" ON whatsapp_connections FOR SELECT
  USING (org_id = public.user_org_id() AND public.is_manager());

CREATE POLICY "whatsapp_manager_insert" ON whatsapp_connections FOR INSERT
  WITH CHECK (org_id = public.user_org_id() AND public.is_manager());

CREATE POLICY "whatsapp_manager_update" ON whatsapp_connections FOR UPDATE
  USING (org_id = public.user_org_id() AND public.is_manager());

CREATE POLICY "whatsapp_manager_delete" ON whatsapp_connections FOR DELETE
  USING (org_id = public.user_org_id() AND public.is_manager());

-- [HIGH #8] Calendar Connections — user owns their own
CREATE POLICY "calendar_own_read" ON calendar_connections FOR SELECT
  USING (org_id = public.user_org_id() AND user_id = auth.uid());

CREATE POLICY "calendar_own_insert" ON calendar_connections FOR INSERT
  WITH CHECK (org_id = public.user_org_id() AND user_id = auth.uid());

CREATE POLICY "calendar_own_update" ON calendar_connections FOR UPDATE
  USING (org_id = public.user_org_id() AND user_id = auth.uid());

CREATE POLICY "calendar_own_delete" ON calendar_connections FOR DELETE
  USING (org_id = public.user_org_id() AND user_id = auth.uid());

-- ============================================================================
-- 8. TRIGGERS
-- ============================================================================

-- 8.1 Auto-update updated_at
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply to all tables with updated_at
CREATE TRIGGER set_updated_at BEFORE UPDATE ON organizations
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON organization_members
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON leads
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON cadences
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON message_templates
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON cadence_enrollments
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON crm_connections
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON subscriptions
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON gmail_connections
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON whatsapp_connections
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON calendar_connections
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON plans
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- 8.2 Auto-create org on user signup
-- [HIGH #10] Com tratamento de plano inexistente
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
  org_name TEXT;
  org_slug TEXT;
  new_org_id UUID;
  starter_plan_id UUID;
BEGIN
  org_name := split_part(NEW.email, '@', 2);
  org_slug := lower(replace(org_name, '.', '-')) || '-' || substr(gen_random_uuid()::text, 1, 8);

  INSERT INTO organizations (name, slug, owner_id)
  VALUES (org_name, org_slug, NEW.id)
  RETURNING id INTO new_org_id;

  INSERT INTO organization_members (org_id, user_id, role, status, accepted_at)
  VALUES (new_org_id, NEW.id, 'manager', 'active', now());

  -- Create trial subscription (with safety check)
  SELECT id INTO starter_plan_id FROM plans WHERE slug = 'starter' AND active = true LIMIT 1;

  IF starter_plan_id IS NOT NULL THEN
    INSERT INTO subscriptions (org_id, plan_id, status)
    VALUES (new_org_id, starter_plan_id, 'trialing');
  ELSE
    RAISE WARNING '[handle_new_user] Plan "starter" not found. Subscription NOT created for user %. Run seed data.', NEW.id;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_new_user();

-- 8.3 Calculate next_step_due when enrollment changes
CREATE OR REPLACE FUNCTION calculate_next_step_due()
RETURNS TRIGGER AS $$
DECLARE
  step RECORD;
BEGIN
  IF NEW.status = 'active' THEN
    SELECT delay_days, delay_hours INTO step
    FROM cadence_steps
    WHERE cadence_id = NEW.cadence_id AND step_order = NEW.current_step;

    IF FOUND THEN
      NEW.next_step_due := now() + make_interval(days => step.delay_days, hours => step.delay_hours);
    ELSE
      -- Step not found — enrollment may have completed all steps
      NEW.next_step_due := NULL;
    END IF;
  ELSIF NEW.status IN ('completed', 'replied', 'bounced', 'unsubscribed') THEN
    NEW.next_step_due := NULL;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_next_step_due
  BEFORE INSERT OR UPDATE OF current_step, status ON cadence_enrollments
  FOR EACH ROW EXECUTE FUNCTION calculate_next_step_due();

-- ============================================================================
-- 9. SCHEDULED JOBS (pg_cron)
-- ============================================================================

-- 9.1 Execute cadence steps every 15 minutes
SELECT cron.schedule('execute-cadence-steps', '*/15 * * * *',
  $$ SELECT net.http_post(
    url := current_setting('app.supabase_url') || '/functions/v1/execute-cadence-steps',
    headers := jsonb_build_object('Authorization', 'Bearer ' || current_setting('app.service_role_key')),
    body := '{}'::jsonb
  ) $$
);

-- 9.2 Batch CRM sync every 30 minutes
SELECT cron.schedule('sync-crm', '*/30 * * * *',
  $$ SELECT net.http_post(
    url := current_setting('app.supabase_url') || '/functions/v1/sync-crm',
    headers := jsonb_build_object('Authorization', 'Bearer ' || current_setting('app.service_role_key')),
    body := '{}'::jsonb
  ) $$
);

-- [LOW #19] Renomeado: cleanup, não reset
-- 9.3 Cleanup AI usage history older than 90 days (São Paulo midnight = 03:00 UTC)
SELECT cron.schedule('cleanup-ai-usage-history', '0 3 * * *',
  $$ DELETE FROM ai_usage WHERE usage_date < CURRENT_DATE - INTERVAL '90 days' $$
);

-- 9.4 Create monthly WhatsApp credits on 1st of month
SELECT cron.schedule('create-monthly-wa-credits', '0 3 1 * *',
  $$ INSERT INTO whatsapp_credits (org_id, plan_credits, used_credits, period)
     SELECT s.org_id, p.max_whatsapp_per_month, 0, to_char(CURRENT_DATE, 'YYYY-MM')
     FROM subscriptions s JOIN plans p ON s.plan_id = p.id
     WHERE s.status IN ('active', 'trialing')
     ON CONFLICT (org_id, period) DO NOTHING $$
);

-- ============================================================================
-- 10. SEED DATA
-- ============================================================================

INSERT INTO plans (name, slug, price_cents, max_leads, max_ai_per_day, max_whatsapp_per_month, included_users, additional_user_price_cents, features) VALUES
  ('Starter', 'starter', 14900, 1000, 50, 500, 4, 4900, '{"enrichment": "basic", "crm": false, "calendar": false}'::jsonb),
  ('Pro', 'pro', 34900, 5000, 200, 2500, 4, 8900, '{"enrichment": "lemit", "crm": true, "calendar": true}'::jsonb),
  ('Enterprise', 'enterprise', 69900, 10000, -1, 10000, 4, 12900, '{"enrichment": "full", "crm": true, "calendar": true}'::jsonb)
ON CONFLICT (slug) DO NOTHING;

COMMIT;
