BEGIN;

ALTER TABLE cadences
  ADD COLUMN IF NOT EXISTS auto_loss_after_days INTEGER DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS auto_loss_reason_id UUID REFERENCES loss_reasons(id) ON DELETE SET NULL DEFAULT NULL;

COMMIT;
